name: Pull request checks

on:
  pull_request:

jobs:
  deploy:
    name: Perform PR checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install wheel
          python -m pip install -e .[test]
      - name: Lint
        run: |
          flake8 src tests
      - name: Test
        run: py.test tests/ --cov=commercetools_token_refresher --cov-report=xml --cov-report=term-missing --junit-xml=reports/junit.xml --cov-fail-under=${{ env.MIN_COVERAGE }}
        env:
          CI: 1
          MIN_COVERAGE: 30
